name: ambliopia_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flame: ^1.37.0
  flame_audio: ^2.12.1
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/piano_hit.wav
    - assets/audio/piano_miss.wav